### ISSUE TITLE
Building on Ubuntu Server 15.10

### ISSUE THREAD

**Issue by dkeller93** [boos/bluesnarfer#1]
Hello. I tried building on Ubuntu Server 15.10.
I did `sudo apt-get install bluetooth libbluetooth-dev -y; git clone https://github.com/boos/bluesnarfer; cd bluesnarfer; make` but I get a bunch of undefined references to hci_*

**Comment by boos** [comment]
Try again now with latest master and confirm if you can or cannot compile it properly.

**Comment by boos** [comment]
I'll close this ticket in 5 days.
